### ISSUE TITLE
Installable Web App (PWA)

### ISSUE THREAD

**Issue by mrdoob** [steveruizok/globs#6]
Have you considered making globs installable?

Example:

<img width="347" alt="Screenshot 2021-04-15 at 10 46 46" src="https://user-images.githubusercontent.com/97088/114849767-fc382700-9dd7-11eb-9511-6386c8bb4e5c.png">

If so, here is all you need:

* Manifest
  * https://github.com/mrdoob/frame.js/blob/master/index.html#L7
  * https://github.com/mrdoob/frame.js/blob/master/manifest.json
  * https://github.com/mrdoob/frame.js/blob/master/files/icon.png
* Service Worker
  * https://github.com/mrdoob/frame.js/blob/master/index.html#L190-L202
  * https://github.com/mrdoob/frame.js/blob/master/sw.js

Once installed, globs would look something like this:

<img width="1312" alt="Screenshot 2021-04-15 at 10 47 05" src="https://user-images.githubusercontent.com/97088/114849865-196cf580-9dd8-11eb-9a21-01ec0ab25a66.png">

**Comment by steveruizok** [comment]
I'll take a shot!
